// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: base.proto
// Protobuf C++ Version: 6.33.4

#ifndef base_2eproto_2epb_2eh
#define base_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "transform.pb.h"
#include "session.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_base_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_base_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_base_2eproto;
}  // extern "C"
namespace idtxcore {
class BaseMessage;
struct BaseMessageDefaultTypeInternal;
extern BaseMessageDefaultTypeInternal _BaseMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BaseMessage_class_data_;
class Handshake;
struct HandshakeDefaultTypeInternal;
extern HandshakeDefaultTypeInternal _Handshake_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Handshake_class_data_;
}  // namespace idtxcore
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace idtxcore {

// ===================================================================


// -------------------------------------------------------------------

class Handshake final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:idtxcore.Handshake) */ {
 public:
  inline Handshake() : Handshake(nullptr) {}
  ~Handshake() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Handshake* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Handshake));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Handshake(::google::protobuf::internal::ConstantInitialized);

  inline Handshake(const Handshake& from) : Handshake(nullptr, from) {}
  inline Handshake(Handshake&& from) noexcept
      : Handshake(nullptr, ::std::move(from)) {}
  inline Handshake& operator=(const Handshake& from) {
    CopyFrom(from);
    return *this;
  }
  inline Handshake& operator=(Handshake&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Handshake& default_instance() {
    return *reinterpret_cast<const Handshake*>(
        &_Handshake_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Handshake& a, Handshake& b) { a.Swap(&b); }
  inline void Swap(Handshake* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Handshake* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Handshake* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Handshake>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Handshake& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Handshake& from) { Handshake::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Handshake* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "idtxcore.Handshake"; }

  explicit Handshake(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Handshake(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Handshake& from);
  Handshake(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Handshake&& from) noexcept
      : Handshake(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kSessionLayerFieldNumber = 2,
    kUsdPathFieldNumber = 3,
    kUsdUriFieldNumber = 4,
  };
  // string session_id = 1;
  void clear_session_id() ;
  const ::std::string& session_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_id();
  void set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_id();

  public:
  // string session_layer = 2;
  void clear_session_layer() ;
  const ::std::string& session_layer() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_layer(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_layer();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_layer();
  void set_allocated_session_layer(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_layer() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_layer(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_layer();

  public:
  // string usd_path = 3;
  void clear_usd_path() ;
  const ::std::string& usd_path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_usd_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_usd_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_usd_path();
  void set_allocated_usd_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_usd_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_usd_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_usd_path();

  public:
  // string usd_uri = 4;
  void clear_usd_uri() ;
  const ::std::string& usd_uri() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_usd_uri(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_usd_uri();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_usd_uri();
  void set_allocated_usd_uri(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_usd_uri() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_usd_uri(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_usd_uri();

  public:
  // @@protoc_insertion_point(class_scope:idtxcore.Handshake)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 65,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Handshake& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_id_;
    ::google::protobuf::internal::ArenaStringPtr session_layer_;
    ::google::protobuf::internal::ArenaStringPtr usd_path_;
    ::google::protobuf::internal::ArenaStringPtr usd_uri_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Handshake_class_data_;
// -------------------------------------------------------------------

class BaseMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:idtxcore.BaseMessage) */ {
 public:
  inline BaseMessage() : BaseMessage(nullptr) {}
  ~BaseMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BaseMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BaseMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BaseMessage(::google::protobuf::internal::ConstantInitialized);

  inline BaseMessage(const BaseMessage& from) : BaseMessage(nullptr, from) {}
  inline BaseMessage(BaseMessage&& from) noexcept
      : BaseMessage(nullptr, ::std::move(from)) {}
  inline BaseMessage& operator=(const BaseMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline BaseMessage& operator=(BaseMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BaseMessage& default_instance() {
    return *reinterpret_cast<const BaseMessage*>(
        &_BaseMessage_default_instance_);
  }
  enum MessageCase {
    kHandshake = 2,
    kXformUpdate = 3,
    kXformBroadcast = 4,
    kAck = 5,
    kError = 6,
    MESSAGE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BaseMessage& a, BaseMessage& b) { a.Swap(&b); }
  inline void Swap(BaseMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BaseMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BaseMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BaseMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BaseMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BaseMessage& from) { BaseMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BaseMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "idtxcore.BaseMessage"; }

  explicit BaseMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BaseMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BaseMessage& from);
  BaseMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BaseMessage&& from) noexcept
      : BaseMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSessionIdFieldNumber = 1,
    kHandshakeFieldNumber = 2,
    kXformUpdateFieldNumber = 3,
    kXformBroadcastFieldNumber = 4,
    kAckFieldNumber = 5,
    kErrorFieldNumber = 6,
  };
  // optional string session_id = 1;
  bool has_session_id() const;
  void clear_session_id() ;
  const ::std::string& session_id() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_session_id(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_session_id();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_session_id();
  void set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_session_id() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_session_id(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_session_id();

  public:
  // .idtxcore.Handshake handshake = 2;
  bool has_handshake() const;
  private:
  bool _internal_has_handshake() const;

  public:
  void clear_handshake() ;
  const ::idtxcore::Handshake& handshake() const;
  [[nodiscard]] ::idtxcore::Handshake* PROTOBUF_NULLABLE release_handshake();
  ::idtxcore::Handshake* PROTOBUF_NONNULL mutable_handshake();
  void set_allocated_handshake(::idtxcore::Handshake* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_handshake(::idtxcore::Handshake* PROTOBUF_NULLABLE value);
  ::idtxcore::Handshake* PROTOBUF_NULLABLE unsafe_arena_release_handshake();

  private:
  const ::idtxcore::Handshake& _internal_handshake() const;
  ::idtxcore::Handshake* PROTOBUF_NONNULL _internal_mutable_handshake();

  public:
  // .idtxcore.TransformUpdate xform_update = 3;
  bool has_xform_update() const;
  private:
  bool _internal_has_xform_update() const;

  public:
  void clear_xform_update() ;
  const ::idtxcore::TransformUpdate& xform_update() const;
  [[nodiscard]] ::idtxcore::TransformUpdate* PROTOBUF_NULLABLE release_xform_update();
  ::idtxcore::TransformUpdate* PROTOBUF_NONNULL mutable_xform_update();
  void set_allocated_xform_update(::idtxcore::TransformUpdate* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_xform_update(::idtxcore::TransformUpdate* PROTOBUF_NULLABLE value);
  ::idtxcore::TransformUpdate* PROTOBUF_NULLABLE unsafe_arena_release_xform_update();

  private:
  const ::idtxcore::TransformUpdate& _internal_xform_update() const;
  ::idtxcore::TransformUpdate* PROTOBUF_NONNULL _internal_mutable_xform_update();

  public:
  // .idtxcore.TransformBroadcast xform_broadcast = 4;
  bool has_xform_broadcast() const;
  private:
  bool _internal_has_xform_broadcast() const;

  public:
  void clear_xform_broadcast() ;
  const ::idtxcore::TransformBroadcast& xform_broadcast() const;
  [[nodiscard]] ::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE release_xform_broadcast();
  ::idtxcore::TransformBroadcast* PROTOBUF_NONNULL mutable_xform_broadcast();
  void set_allocated_xform_broadcast(::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_xform_broadcast(::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE value);
  ::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE unsafe_arena_release_xform_broadcast();

  private:
  const ::idtxcore::TransformBroadcast& _internal_xform_broadcast() const;
  ::idtxcore::TransformBroadcast* PROTOBUF_NONNULL _internal_mutable_xform_broadcast();

  public:
  // .idtxcore.Ack ack = 5;
  bool has_ack() const;
  private:
  bool _internal_has_ack() const;

  public:
  void clear_ack() ;
  const ::idtxcore::Ack& ack() const;
  [[nodiscard]] ::idtxcore::Ack* PROTOBUF_NULLABLE release_ack();
  ::idtxcore::Ack* PROTOBUF_NONNULL mutable_ack();
  void set_allocated_ack(::idtxcore::Ack* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ack(::idtxcore::Ack* PROTOBUF_NULLABLE value);
  ::idtxcore::Ack* PROTOBUF_NULLABLE unsafe_arena_release_ack();

  private:
  const ::idtxcore::Ack& _internal_ack() const;
  ::idtxcore::Ack* PROTOBUF_NONNULL _internal_mutable_ack();

  public:
  // .idtxcore.Error error = 6;
  bool has_error() const;
  private:
  bool _internal_has_error() const;

  public:
  void clear_error() ;
  const ::idtxcore::Error& error() const;
  [[nodiscard]] ::idtxcore::Error* PROTOBUF_NULLABLE release_error();
  ::idtxcore::Error* PROTOBUF_NONNULL mutable_error();
  void set_allocated_error(::idtxcore::Error* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_error(::idtxcore::Error* PROTOBUF_NULLABLE value);
  ::idtxcore::Error* PROTOBUF_NULLABLE unsafe_arena_release_error();

  private:
  const ::idtxcore::Error& _internal_error() const;
  ::idtxcore::Error* PROTOBUF_NONNULL _internal_mutable_error();

  public:
  void clear_message();
  MessageCase message_case() const;
  // @@protoc_insertion_point(class_scope:idtxcore.BaseMessage)
 private:
  class _Internal;
  void set_has_handshake();
  void set_has_xform_update();
  void set_has_xform_broadcast();
  void set_has_ack();
  void set_has_error();
  inline bool has_message() const;
  inline void clear_has_message();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 6,
                                   5, 39,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BaseMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr session_id_;
    union MessageUnion {
      constexpr MessageUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE handshake_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE xform_update_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE xform_broadcast_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE ack_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE error_;
    } message_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_base_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BaseMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Handshake

// string session_id = 1;
inline void Handshake::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Handshake::session_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.session_id)
  return _internal_session_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Handshake::set_session_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.session_id)
}
inline ::std::string* PROTOBUF_NONNULL Handshake::mutable_session_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.session_id)
  return _s;
}
inline const ::std::string& Handshake::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_.Get();
}
inline void Handshake::_internal_set_session_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Handshake::_internal_mutable_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Handshake::release_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.session_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_id_.Set("", GetArena());
  }
  return released;
}
inline void Handshake::set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.session_id)
}

// string session_layer = 2;
inline void Handshake::clear_session_layer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_layer_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Handshake::session_layer() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.session_layer)
  return _internal_session_layer();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Handshake::set_session_layer(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.session_layer_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.session_layer)
}
inline ::std::string* PROTOBUF_NONNULL Handshake::mutable_session_layer()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_session_layer();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.session_layer)
  return _s;
}
inline const ::std::string& Handshake::_internal_session_layer() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_layer_.Get();
}
inline void Handshake::_internal_set_session_layer(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_layer_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Handshake::_internal_mutable_session_layer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_layer_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Handshake::release_session_layer() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.session_layer)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.session_layer_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_layer_.Set("", GetArena());
  }
  return released;
}
inline void Handshake::set_allocated_session_layer(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.session_layer_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_layer_.IsDefault()) {
    _impl_.session_layer_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.session_layer)
}

// string usd_path = 3;
inline void Handshake::clear_usd_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usd_path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& Handshake::usd_path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.usd_path)
  return _internal_usd_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Handshake::set_usd_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.usd_path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.usd_path)
}
inline ::std::string* PROTOBUF_NONNULL Handshake::mutable_usd_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_usd_path();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.usd_path)
  return _s;
}
inline const ::std::string& Handshake::_internal_usd_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.usd_path_.Get();
}
inline void Handshake::_internal_set_usd_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usd_path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Handshake::_internal_mutable_usd_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.usd_path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Handshake::release_usd_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.usd_path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.usd_path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.usd_path_.Set("", GetArena());
  }
  return released;
}
inline void Handshake::set_allocated_usd_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.usd_path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.usd_path_.IsDefault()) {
    _impl_.usd_path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.usd_path)
}

// string usd_uri = 4;
inline void Handshake::clear_usd_uri() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usd_uri_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& Handshake::usd_uri() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.Handshake.usd_uri)
  return _internal_usd_uri();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Handshake::set_usd_uri(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.usd_uri_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:idtxcore.Handshake.usd_uri)
}
inline ::std::string* PROTOBUF_NONNULL Handshake::mutable_usd_uri()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_usd_uri();
  // @@protoc_insertion_point(field_mutable:idtxcore.Handshake.usd_uri)
  return _s;
}
inline const ::std::string& Handshake::_internal_usd_uri() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.usd_uri_.Get();
}
inline void Handshake::_internal_set_usd_uri(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usd_uri_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Handshake::_internal_mutable_usd_uri() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.usd_uri_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Handshake::release_usd_uri() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:idtxcore.Handshake.usd_uri)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.usd_uri_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.usd_uri_.Set("", GetArena());
  }
  return released;
}
inline void Handshake::set_allocated_usd_uri(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.usd_uri_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.usd_uri_.IsDefault()) {
    _impl_.usd_uri_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.Handshake.usd_uri)
}

// -------------------------------------------------------------------

// BaseMessage

// optional string session_id = 1;
inline bool BaseMessage::has_session_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void BaseMessage::clear_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& BaseMessage::session_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.session_id)
  return _internal_session_id();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void BaseMessage::set_session_id(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.session_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:idtxcore.BaseMessage.session_id)
}
inline ::std::string* PROTOBUF_NONNULL BaseMessage::mutable_session_id()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_session_id();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.session_id)
  return _s;
}
inline const ::std::string& BaseMessage::_internal_session_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.session_id_.Get();
}
inline void BaseMessage::_internal_set_session_id(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.session_id_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL BaseMessage::_internal_mutable_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.session_id_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE BaseMessage::release_session_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.session_id)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.session_id_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.session_id_.Set("", GetArena());
  }
  return released;
}
inline void BaseMessage::set_allocated_session_id(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.session_id_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.session_id_.IsDefault()) {
    _impl_.session_id_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:idtxcore.BaseMessage.session_id)
}

// .idtxcore.Handshake handshake = 2;
inline bool BaseMessage::has_handshake() const {
  return message_case() == kHandshake;
}
inline bool BaseMessage::_internal_has_handshake() const {
  return message_case() == kHandshake;
}
inline void BaseMessage::set_has_handshake() {
  _impl_._oneof_case_[0] = kHandshake;
}
inline void BaseMessage::clear_handshake() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_case() == kHandshake) {
    if (GetArena() == nullptr) {
      delete _impl_.message_.handshake_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.message_.handshake_);
    }
    clear_has_message();
  }
}
inline ::idtxcore::Handshake* PROTOBUF_NULLABLE BaseMessage::release_handshake() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.handshake)
  if (message_case() == kHandshake) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Handshake*>(_impl_.message_.handshake_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.handshake_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Handshake& BaseMessage::_internal_handshake() const {
  return message_case() == kHandshake ? static_cast<const ::idtxcore::Handshake&>(*reinterpret_cast<::idtxcore::Handshake*>(_impl_.message_.handshake_))
                     : reinterpret_cast<const ::idtxcore::Handshake&>(::idtxcore::_Handshake_default_instance_);
}
inline const ::idtxcore::Handshake& BaseMessage::handshake() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.handshake)
  return _internal_handshake();
}
inline ::idtxcore::Handshake* PROTOBUF_NULLABLE BaseMessage::unsafe_arena_release_handshake() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.handshake)
  if (message_case() == kHandshake) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Handshake*>(_impl_.message_.handshake_);
    _impl_.message_.handshake_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_handshake(
    ::idtxcore::Handshake* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_handshake();
    _impl_.message_.handshake_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.handshake)
}
inline ::idtxcore::Handshake* PROTOBUF_NONNULL BaseMessage::_internal_mutable_handshake() {
  if (message_case() != kHandshake) {
    clear_message();
    set_has_handshake();
    _impl_.message_.handshake_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::idtxcore::Handshake>(GetArena()));
  }
  return reinterpret_cast<::idtxcore::Handshake*>(_impl_.message_.handshake_);
}
inline ::idtxcore::Handshake* PROTOBUF_NONNULL BaseMessage::mutable_handshake()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::idtxcore::Handshake* _msg = _internal_mutable_handshake();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.handshake)
  return _msg;
}

// .idtxcore.TransformUpdate xform_update = 3;
inline bool BaseMessage::has_xform_update() const {
  return message_case() == kXformUpdate;
}
inline bool BaseMessage::_internal_has_xform_update() const {
  return message_case() == kXformUpdate;
}
inline void BaseMessage::set_has_xform_update() {
  _impl_._oneof_case_[0] = kXformUpdate;
}
inline ::idtxcore::TransformUpdate* PROTOBUF_NULLABLE BaseMessage::release_xform_update() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.xform_update)
  if (message_case() == kXformUpdate) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::TransformUpdate*>(_impl_.message_.xform_update_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.xform_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::TransformUpdate& BaseMessage::_internal_xform_update() const {
  return message_case() == kXformUpdate ? static_cast<const ::idtxcore::TransformUpdate&>(*reinterpret_cast<::idtxcore::TransformUpdate*>(_impl_.message_.xform_update_))
                     : reinterpret_cast<const ::idtxcore::TransformUpdate&>(::idtxcore::_TransformUpdate_default_instance_);
}
inline const ::idtxcore::TransformUpdate& BaseMessage::xform_update() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.xform_update)
  return _internal_xform_update();
}
inline ::idtxcore::TransformUpdate* PROTOBUF_NULLABLE BaseMessage::unsafe_arena_release_xform_update() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.xform_update)
  if (message_case() == kXformUpdate) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::TransformUpdate*>(_impl_.message_.xform_update_);
    _impl_.message_.xform_update_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_xform_update(
    ::idtxcore::TransformUpdate* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_xform_update();
    _impl_.message_.xform_update_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.xform_update)
}
inline ::idtxcore::TransformUpdate* PROTOBUF_NONNULL BaseMessage::_internal_mutable_xform_update() {
  if (message_case() != kXformUpdate) {
    clear_message();
    set_has_xform_update();
    _impl_.message_.xform_update_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::idtxcore::TransformUpdate>(GetArena()));
  }
  return reinterpret_cast<::idtxcore::TransformUpdate*>(_impl_.message_.xform_update_);
}
inline ::idtxcore::TransformUpdate* PROTOBUF_NONNULL BaseMessage::mutable_xform_update()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::idtxcore::TransformUpdate* _msg = _internal_mutable_xform_update();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.xform_update)
  return _msg;
}

// .idtxcore.TransformBroadcast xform_broadcast = 4;
inline bool BaseMessage::has_xform_broadcast() const {
  return message_case() == kXformBroadcast;
}
inline bool BaseMessage::_internal_has_xform_broadcast() const {
  return message_case() == kXformBroadcast;
}
inline void BaseMessage::set_has_xform_broadcast() {
  _impl_._oneof_case_[0] = kXformBroadcast;
}
inline ::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE BaseMessage::release_xform_broadcast() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.xform_broadcast)
  if (message_case() == kXformBroadcast) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::TransformBroadcast*>(_impl_.message_.xform_broadcast_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.xform_broadcast_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::TransformBroadcast& BaseMessage::_internal_xform_broadcast() const {
  return message_case() == kXformBroadcast ? static_cast<const ::idtxcore::TransformBroadcast&>(*reinterpret_cast<::idtxcore::TransformBroadcast*>(_impl_.message_.xform_broadcast_))
                     : reinterpret_cast<const ::idtxcore::TransformBroadcast&>(::idtxcore::_TransformBroadcast_default_instance_);
}
inline const ::idtxcore::TransformBroadcast& BaseMessage::xform_broadcast() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.xform_broadcast)
  return _internal_xform_broadcast();
}
inline ::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE BaseMessage::unsafe_arena_release_xform_broadcast() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.xform_broadcast)
  if (message_case() == kXformBroadcast) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::TransformBroadcast*>(_impl_.message_.xform_broadcast_);
    _impl_.message_.xform_broadcast_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_xform_broadcast(
    ::idtxcore::TransformBroadcast* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_xform_broadcast();
    _impl_.message_.xform_broadcast_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.xform_broadcast)
}
inline ::idtxcore::TransformBroadcast* PROTOBUF_NONNULL BaseMessage::_internal_mutable_xform_broadcast() {
  if (message_case() != kXformBroadcast) {
    clear_message();
    set_has_xform_broadcast();
    _impl_.message_.xform_broadcast_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::idtxcore::TransformBroadcast>(GetArena()));
  }
  return reinterpret_cast<::idtxcore::TransformBroadcast*>(_impl_.message_.xform_broadcast_);
}
inline ::idtxcore::TransformBroadcast* PROTOBUF_NONNULL BaseMessage::mutable_xform_broadcast()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::idtxcore::TransformBroadcast* _msg = _internal_mutable_xform_broadcast();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.xform_broadcast)
  return _msg;
}

// .idtxcore.Ack ack = 5;
inline bool BaseMessage::has_ack() const {
  return message_case() == kAck;
}
inline bool BaseMessage::_internal_has_ack() const {
  return message_case() == kAck;
}
inline void BaseMessage::set_has_ack() {
  _impl_._oneof_case_[0] = kAck;
}
inline ::idtxcore::Ack* PROTOBUF_NULLABLE BaseMessage::release_ack() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.ack)
  if (message_case() == kAck) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Ack*>(_impl_.message_.ack_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Ack& BaseMessage::_internal_ack() const {
  return message_case() == kAck ? static_cast<const ::idtxcore::Ack&>(*reinterpret_cast<::idtxcore::Ack*>(_impl_.message_.ack_))
                     : reinterpret_cast<const ::idtxcore::Ack&>(::idtxcore::_Ack_default_instance_);
}
inline const ::idtxcore::Ack& BaseMessage::ack() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.ack)
  return _internal_ack();
}
inline ::idtxcore::Ack* PROTOBUF_NULLABLE BaseMessage::unsafe_arena_release_ack() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.ack)
  if (message_case() == kAck) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Ack*>(_impl_.message_.ack_);
    _impl_.message_.ack_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_ack(
    ::idtxcore::Ack* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_ack();
    _impl_.message_.ack_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.ack)
}
inline ::idtxcore::Ack* PROTOBUF_NONNULL BaseMessage::_internal_mutable_ack() {
  if (message_case() != kAck) {
    clear_message();
    set_has_ack();
    _impl_.message_.ack_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::idtxcore::Ack>(GetArena()));
  }
  return reinterpret_cast<::idtxcore::Ack*>(_impl_.message_.ack_);
}
inline ::idtxcore::Ack* PROTOBUF_NONNULL BaseMessage::mutable_ack()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::idtxcore::Ack* _msg = _internal_mutable_ack();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.ack)
  return _msg;
}

// .idtxcore.Error error = 6;
inline bool BaseMessage::has_error() const {
  return message_case() == kError;
}
inline bool BaseMessage::_internal_has_error() const {
  return message_case() == kError;
}
inline void BaseMessage::set_has_error() {
  _impl_._oneof_case_[0] = kError;
}
inline ::idtxcore::Error* PROTOBUF_NULLABLE BaseMessage::release_error() {
  // @@protoc_insertion_point(field_release:idtxcore.BaseMessage.error)
  if (message_case() == kError) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Error*>(_impl_.message_.error_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.message_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::idtxcore::Error& BaseMessage::_internal_error() const {
  return message_case() == kError ? static_cast<const ::idtxcore::Error&>(*reinterpret_cast<::idtxcore::Error*>(_impl_.message_.error_))
                     : reinterpret_cast<const ::idtxcore::Error&>(::idtxcore::_Error_default_instance_);
}
inline const ::idtxcore::Error& BaseMessage::error() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:idtxcore.BaseMessage.error)
  return _internal_error();
}
inline ::idtxcore::Error* PROTOBUF_NULLABLE BaseMessage::unsafe_arena_release_error() {
  // @@protoc_insertion_point(field_unsafe_arena_release:idtxcore.BaseMessage.error)
  if (message_case() == kError) {
    clear_has_message();
    auto* temp = reinterpret_cast<::idtxcore::Error*>(_impl_.message_.error_);
    _impl_.message_.error_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void BaseMessage::unsafe_arena_set_allocated_error(
    ::idtxcore::Error* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_message();
  if (value) {
    set_has_error();
    _impl_.message_.error_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:idtxcore.BaseMessage.error)
}
inline ::idtxcore::Error* PROTOBUF_NONNULL BaseMessage::_internal_mutable_error() {
  if (message_case() != kError) {
    clear_message();
    set_has_error();
    _impl_.message_.error_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::idtxcore::Error>(GetArena()));
  }
  return reinterpret_cast<::idtxcore::Error*>(_impl_.message_.error_);
}
inline ::idtxcore::Error* PROTOBUF_NONNULL BaseMessage::mutable_error()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::idtxcore::Error* _msg = _internal_mutable_error();
  // @@protoc_insertion_point(field_mutable:idtxcore.BaseMessage.error)
  return _msg;
}

inline bool BaseMessage::has_message() const {
  return message_case() != MESSAGE_NOT_SET;
}
inline void BaseMessage::clear_has_message() {
  _impl_._oneof_case_[0] = MESSAGE_NOT_SET;
}
inline BaseMessage::MessageCase BaseMessage::message_case() const {
  return BaseMessage::MessageCase(_impl_._oneof_case_[0]);
}
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace idtxcore


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // base_2eproto_2epb_2eh
